[[libadwaita]]
arch = "aarch64"
git-tree-sha1 = "35272bc13ab514b538775121c78526ac9bc9ec79"
os = "macos"

    [[libadwaita.download]]
    sha256 = "0965826158288ba69195afcf8109e0046ca2f801edc4fd982d54e7d8bd66de01"
    url = "https://github.com/JuliaBinaryWrappers/libadwaita_jll.jl/releases/download/libadwaita-v1.3.6+0/libadwaita.v1.3.6.aarch64-apple-darwin.tar.gz"
[[libadwaita]]
arch = "aarch64"
git-tree-sha1 = "476d845fc9030a9382738b251a793c85b7360887"
libc = "glibc"
os = "linux"

    [[libadwaita.download]]
    sha256 = "149c4036e9723b26219179168ea38ba797d91e81f182f77f70c478101fc38d2d"
    url = "https://github.com/JuliaBinaryWrappers/libadwaita_jll.jl/releases/download/libadwaita-v1.3.6+0/libadwaita.v1.3.6.aarch64-linux-gnu.tar.gz"
[[libadwaita]]
arch = "aarch64"
git-tree-sha1 = "95dc58731cd19f8c6e0d84204be4e4f0f38f4534"
libc = "musl"
os = "linux"

    [[libadwaita.download]]
    sha256 = "8ef93a22c9d742db05fbb77c942609d0c8d435cfd0e0cc00c79b6784ee031522"
    url = "https://github.com/JuliaBinaryWrappers/libadwaita_jll.jl/releases/download/libadwaita-v1.3.6+0/libadwaita.v1.3.6.aarch64-linux-musl.tar.gz"
[[libadwaita]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a02b3358733196043e6a76ae290991c635dceed4"
libc = "glibc"
os = "linux"

    [[libadwaita.download]]
    sha256 = "71e7b48ac8d49aafc485d645abe902323bc6cf1110f088712c80068fc9703141"
    url = "https://github.com/JuliaBinaryWrappers/libadwaita_jll.jl/releases/download/libadwaita-v1.3.6+0/libadwaita.v1.3.6.armv7l-linux-gnueabihf.tar.gz"
[[libadwaita]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f80258cea55032731b574b372b7635b9af75065f"
libc = "musl"
os = "linux"

    [[libadwaita.download]]
    sha256 = "33b2b3c4a653c1f98eaae693e9d2cbeca038a049f09eeaaedeb4acfa339cac36"
    url = "https://github.com/JuliaBinaryWrappers/libadwaita_jll.jl/releases/download/libadwaita-v1.3.6+0/libadwaita.v1.3.6.armv7l-linux-musleabihf.tar.gz"
[[libadwaita]]
arch = "i686"
git-tree-sha1 = "ea59fc76f1bb1aea4cd7552c839c8b4d1552b4c1"
libc = "glibc"
os = "linux"

    [[libadwaita.download]]
    sha256 = "de9396e28e53fd9561485323acbca360f41f1b5272c27f705c0856a939d4bfbc"
    url = "https://github.com/JuliaBinaryWrappers/libadwaita_jll.jl/releases/download/libadwaita-v1.3.6+0/libadwaita.v1.3.6.i686-linux-gnu.tar.gz"
[[libadwaita]]
arch = "i686"
git-tree-sha1 = "ac9e897c2896b5e6973633a0c5b255f0653fd1a0"
libc = "musl"
os = "linux"

    [[libadwaita.download]]
    sha256 = "fe64b33a269a7a64b09f5c1e068d43ab1260e9c338d9c4c83db22531bbdb327e"
    url = "https://github.com/JuliaBinaryWrappers/libadwaita_jll.jl/releases/download/libadwaita-v1.3.6+0/libadwaita.v1.3.6.i686-linux-musl.tar.gz"
[[libadwaita]]
arch = "i686"
git-tree-sha1 = "7862073b7beae14854786d3755e680575d0e6d3e"
os = "windows"

    [[libadwaita.download]]
    sha256 = "8d45fdba56bca74ce809cf74c6cdc44a1c52c1085483d69881042bb30086a6f3"
    url = "https://github.com/JuliaBinaryWrappers/libadwaita_jll.jl/releases/download/libadwaita-v1.3.6+0/libadwaita.v1.3.6.i686-w64-mingw32.tar.gz"
[[libadwaita]]
arch = "powerpc64le"
git-tree-sha1 = "871d516a729cbec30b067426375484d2aa1a0078"
libc = "glibc"
os = "linux"

    [[libadwaita.download]]
    sha256 = "4614717d4e6da8581113ba130cb9f46765af41613fb4436bb75b1002f14cd29d"
    url = "https://github.com/JuliaBinaryWrappers/libadwaita_jll.jl/releases/download/libadwaita-v1.3.6+0/libadwaita.v1.3.6.powerpc64le-linux-gnu.tar.gz"
[[libadwaita]]
arch = "x86_64"
git-tree-sha1 = "25651755669ca5f69e51c3447e400ef0e4ae7a72"
os = "macos"

    [[libadwaita.download]]
    sha256 = "a94868fba6b5419dc5b72aae5a77fbc266396522844e3faf96e94571276497b2"
    url = "https://github.com/JuliaBinaryWrappers/libadwaita_jll.jl/releases/download/libadwaita-v1.3.6+0/libadwaita.v1.3.6.x86_64-apple-darwin.tar.gz"
[[libadwaita]]
arch = "x86_64"
git-tree-sha1 = "3c9b952110cb3325ae6cf230b9b0da1d1fab4b55"
libc = "glibc"
os = "linux"

    [[libadwaita.download]]
    sha256 = "dc3e5abe1a018369b8d07099508fae7b5a649b46aa8ef7bc4ec4afedbf6eb322"
    url = "https://github.com/JuliaBinaryWrappers/libadwaita_jll.jl/releases/download/libadwaita-v1.3.6+0/libadwaita.v1.3.6.x86_64-linux-gnu.tar.gz"
[[libadwaita]]
arch = "x86_64"
git-tree-sha1 = "1149e9167f2cafa96a8e628b26bff8610536a84b"
libc = "musl"
os = "linux"

    [[libadwaita.download]]
    sha256 = "e07d86599575dd08c097e1f45497d1efc71b6e6ef099a93193ce1fa1d40b7e42"
    url = "https://github.com/JuliaBinaryWrappers/libadwaita_jll.jl/releases/download/libadwaita-v1.3.6+0/libadwaita.v1.3.6.x86_64-linux-musl.tar.gz"
[[libadwaita]]
arch = "x86_64"
git-tree-sha1 = "bde13eb3f1f378014f2db4230909c43da1ec1ea8"
os = "freebsd"

    [[libadwaita.download]]
    sha256 = "973a48f9649b0f0bef3d66e59e017669c57e655d4b3eb27edc1d8122aa8f0ad8"
    url = "https://github.com/JuliaBinaryWrappers/libadwaita_jll.jl/releases/download/libadwaita-v1.3.6+0/libadwaita.v1.3.6.x86_64-unknown-freebsd.tar.gz"
[[libadwaita]]
arch = "x86_64"
git-tree-sha1 = "48477520bd9a265cb7a34922807e67672aa92b5c"
os = "windows"

    [[libadwaita.download]]
    sha256 = "04e3f630d725f8211871187f1c270fcadb431d3c8b4ddc5c5a0c0eb6282b8ddd"
    url = "https://github.com/JuliaBinaryWrappers/libadwaita_jll.jl/releases/download/libadwaita-v1.3.6+0/libadwaita.v1.3.6.x86_64-w64-mingw32.tar.gz"
