# Autogenerated wrapper script for libadwaita_jll for x86_64-apple-darwin
export libadwaita

using GTK4_jll
JLLWrappers.@generate_wrapper_header("libadwaita")
JLLWrappers.@declare_library_product(libadwaita, "@rpath/libadwaita-1.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(GTK4_jll)
    JLLWrappers.@init_library_product(
        libadwaita,
        "lib/libadwaita-1.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
